name: "[Linux] Build go brrrr"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'RobertBeckebans/RBDOOM-3-BFG'
          ref: 'v1.5.1'
          submodules: 'recursive'

      - name: Setup DirectX Shader Compiler
        run: |
          wget 'https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.7.2212.1/linux_dxc_2023_03_01.x86_64.tar.gz'
          mkdir -pv "$HOME/.local/bin"
          tar -xf linux_dxc_2023_03_01.x86_64.tar.gz -C "$HOME/.local/bin" --wildcards --strip-components=1 '**/bin/dxc'
          sudo tar -xf linux_dxc_2023_03_01.x86_64.tar.gz -C "/usr/lib" --wildcards --strip-components=2 '**/lib/libdxcompiler.so'
          sudo tar -xf linux_dxc_2023_03_01.x86_64.tar.gz -C "/usr/lib" --wildcards --strip-components=2 '**/lib/libdxil.so'

      - name: Add Ubuntu PPAs for some packages
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
          sudo apt update

      - name: Install dependencies
        run: |
          sudo apt install -y cmake p7zip-full libsdl2-dev libopenal-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libvulkan-dev

      - name: Build
        run: |
          cmake -G "Unix Makefiles" -S neo -B build -DCMAKE_BUILD_TYPE="Release" -DFFMPEG=OFF -DBINKDEC=ON -DUSE_PRECOMPILED_HEADERS=OFF -Wno-dev
          cmake --build build -- -j $(nproc --all)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RBDoom3BFG
          path: build/RBDoom3BFG
